{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-stack-secret
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: {{ .Values.postgresql.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password }}
  POSTGRES_DB: {{ .Values.postgresql.credentials.db }}
  # pgAdmin
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.credentials.email }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.credentials.password }}
{{- end }}
