{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    {{- if .Values.storageClass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  {{- range $key, $value := .Values.storageClass.parameters }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
{{- end }}
